function PEvs(ga,gd,hd,wb,pc,qc,kb){var ka,y,ha,la,xb,Wa,T,X,lb,l,s,Y,L,d,k,R,G,P=0,U=0,ma,$,t=function(d){X=d.target;for(l=lb=0;X;)lb+=X.offsetLeft,l+=X.offsetTop,X=X.offsetParent;P=d.clientX-lb+document.body.scrollLeft+document.documentElement.scrollLeft;U=d.clientY-l+document.body.scrollTop+document.documentElement.scrollTop};this.getX=function(){return P};this.getY=function(){return U};var Ga=function(d){t(d);ma=P;$=U;la=!0;null!=R&&(xb=(new Date).getTime());null!=L&&L(d)},S=function(d){t(d);
la=!1;null!=Y&&Y(d);null!=R&&(Wa=(new Date).getTime(),T=Wa-xb,300>T&&R(d))},C=function(Xa){t(Xa);3>Math.abs(P-ma)&&3>Math.abs(U-$)||($=ma=-9999,la?null!=d&&d(Xa):null!=k&&k(Xa),null!=G&&B())};this.touchDown=function(d){d.preventDefault();d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();ha=!0;ka=d.changedTouches;y=ka[0];Ga(y)};this.touchUp=function(d){d.preventDefault();d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();ha=!0;ka=d.changedTouches;
y=ka[0];S(y)};this.touchMove=function(d){d.preventDefault();d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();ha=!0;ka=d.changedTouches;y=ka[0];C(y)};this.mouseDown=function(d){d.preventDefault();d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();ha||Ga(d)};this.clearDown=function(){la=!1};this.mouseUp=function(d){d.preventDefault();d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();ha||S(d)};this.mouseClick=function(d){d.preventDefault();
d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();la=!1};this.mouseMove=function(d){d.preventDefault();d.stopImmediatePropagation?d.stopImmediatePropagation():d.stopPropagation();ha||C(d)};this.mouseDragged=function(k){k.preventDefault();k.stopImmediatePropagation?k.stopImmediatePropagation():k.stopPropagation();ha||(t(k),null!=d&&d(k),null!=G&&B())};var B=function(){clearTimeout(s);s=setTimeout(function(){G()},600)};$=ma=U=P=0;L=gd;Y=hd;k=wb;d=pc;R=qc;G=kb;la=ha=!1;ga.addEventListener("touchstart",
this.touchDown,!1);ga.addEventListener("touchend",this.touchUp,!1);ga.addEventListener("touchmove",this.touchMove,!1);ga.addEventListener("pointerdown",this.mouseDown,!1);ga.addEventListener("pointerup",this.mouseUp,!1);ga.addEventListener("pointermove",this.mouseMove,!1);ga.addEventListener("mousedown",this.mouseDown,!1);ga.addEventListener("mouseup",this.mouseUp,!1);ga.addEventListener("mousemove",this.mouseMove,!1);ga.addEventListener("click",this.mouseClick,!1);ga.addEventListener("contextmenu",
function(d){d.preventDefault()},!1);ga.addEventListener("mouseout",function(d){la||(U=P=-1,null!=k&&k(d));la=!1})};var HAniS=new function(){function ga(a,b,c,f,e){this.color=a;this.alpha=1;7<this.color.length&&(this.alpha=parseInt(this.color.substring(7),16)/255,this.color=this.color.substring(0,7),.1>this.alpha&&(this.alpha=.1));this.action=b;this.value=c;this.tip=f;this.poly=e;a=e.split(",");this.xy=[];this.ymin=this.xmin=9999;for(b=this.ymax=this.xmax=0;b<a.length;b++)this.xy[b]=parseInt(a[b].trim(),10),0==b%2?(this.xy[b]<this.xmin&&(this.xmin=this.xy[b]),this.xy[b]>this.xmax&&(this.xmax=this.xy[b])):(this.xy[b]<
this.ymin&&(this.ymin=this.xy[b]),this.xy[b]>this.ymax&&(this.ymax=this.xy[b]));this.height=this.ymax-this.ymin+1;this.width=this.xmax-this.xmin+1;this.can=p("canvas");this.can.height=this.height;this.can.width=this.width;this.ctx=this.can.getContext("2d");this.ctx.imageSmoothingEnabled=!1;this.ctx.fillStyle=this.color;this.ctx.globalAlpha=this.alpha;this.ctx.beginPath();this.ctx.moveTo(this.xy[0]-this.xmin,this.xy[1]-this.ymin);for(b=2;b<this.xy.length;b+=2)this.ctx.lineTo(this.xy[b]-this.xmin,this.xy[b+
1]-this.ymin);this.ctx.closePath();this.ctx.fill()}function gd(a,b,c,f,e){this.overlay=a;this.color=b;this.action=c;this.value=f;this.tip=e}function hd(a,b,c,f,e,d,h,g,k){this.x0=a;this.y0=b;this.icon=null;"icon"==c?(this.icon=new Image,this.icon.hotspot=this,id=!0,this.icon.onload=function(a){this.gotit=!0;this.hotspot.x1=this.hotspot.x0+this.width;this.hotspot.y1=this.hotspot.y0+this.height},this.icon.gotit=!1,this.icon.src=f.trim(),this.y1=this.x1=-1):(this.x1=parseInt(c,10)+a,this.y1=parseInt(f,
10)+b);this.pan=e;this.action=d;this.value=h;this.overlay=g;this.tip=k}function wb(a,b,c,f,e,d,h){this.bg=a;null!=a&&0==this.bg.indexOf("0x")&&(this.bg="#"+this.bg.substring(2));this.fg=b;null!=b&&0==this.fg.indexOf("0x")&&(this.fg="#"+this.fg.substring(2));this.font=c;this.fontHeight=Math.round(1.1*parseInt(c,10));this.scolor=f;null!=f&&0==this.scolor.indexOf("0x")&&(this.scolor="#"+this.scolor.substring(2));this.sblur=e;this.sxoff=d;this.syoff=h}var pc,qc,kb,ka,y,ha,la,xb,Wa,T,X,lb,l,s,Y,L,d,k,
R,G,P,U,ma,$,t,Ga,S,C,B,Xa,Rb,Ia,jd,kd,ld,yb,u,v,na,oa,aa,H,Q,E,ae,pa,Sb,w,zb,Tb,Ub,rc,e,ba,Ja,mb,Qc,md,be,ca,Ab,nb,Ya,da,Ka,ob,Vb,Rc,sc,Wb,Bb,tc,uc,Za,nd,od,D,La,id,Sc,pd,qa,ea,A,Tc,F,Xb,Ma,Uc,Yb,Zb,V,Vc,$a,Cb,ra,W,Na,ab,Oa,Db,$b,Pa,bb,qd,vc,wc,rd,Wc,Eb,Ca,Fb,Gb,Qa,cb,db,xc,sa,ia,fa,Da,wa,Hb,sd,td,ud,ce,eb,ac,yc,bc,vd,cc,Xc,wd,Yc,Ib,x,zc,ta,Ac,xd,fb,dc,ec,Jb,yd,zd,gb,Ad,fc,N,I,Zc,Bc,hb,gc,Cc,Ra,Sa,$c,Dc,Bd,ua,Ta,Ec,Fc,Cd,Gc,Dd,de,ee,Ed,hc,ic,fe,Fd,Kb,pb,Hc,Gd,Hd,Z,jc,Ua,J,Ic,Ea,Id,Jd,Kd,kc,Lb,ad,
qb,Mb,Nb,rb,Ob,Jc,ge,bd,Ld,Md,Pb,he,ie,ib,Nd,cd,Od,Pd,Va,O,Qd,Fa,h,sb,xa,ya,za,Kc,dd,Rd,Sd,lc,ed,tb,fd,Td,Lc,Mc,Aa,ub,Qb,Ud,Nc,Vd,re="N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N".split(" "),se=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame||function(a){setTimeout(a,10)},p=function(a){return document.createElement(a)};this.setup=function(a,b){void 0==b&&(b="MORdivcan");T=document.getElementById(b);T.align=
"center";X=p("div");X.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;");l=p("canvas");l.setAttribute("style","position:absolute;top:0;left:0;z-index:1;");L=p("canvas");L.setAttribute("style","position:absolute;top:0;left:0;z-index:2;");d=L.getContext("2d");d.imageSmoothingEnabled=!1;X.appendChild(l);X.appendChild(L);T.appendChild(X);y=new PEvs(L,
HAniS.down,HAniS.up,HAniS.move,HAniS.drag,null,HAniS.canTip);T.setAttribute("tabindex",0);T.addEventListener("keydown",function(a){37==a.keyCode?(jb(!1),Oc(-1),ja()):39==a.keyCode&&(jb(!1),Oc(1),ja())},!0);w=0;Tb=!1;zb=1;Sb=pa=!0;G=k=0;rc=!0;ma=null;Ub=!0;ba=500;Ja=100;mb=2E3;Qc=30;md=0;ed=6E4;tb=null;lc=!1;Ga=t=null;Bc=Zc=I=N=1;Cc=!1;E=Q=H=aa=oa=na=v=u=0;vc=!1;qa=0;id=!1;bb=null;Mc=Lc=Aa=ub=0;Ia=Sc=Wc=!1;Ec=Fc=hc=ic=0;Ma=Bd=Gc=Kb=Ta=!1;Cb=!0;$a=null;V=-1;Lb=ad=Vc=!1;Od=[1,0,0];Pd=[2,2,1];Va=[];kc=
[];nb=Ab=ia=!1;Ac=zc=0;var c=p("canvas");c.height=1;c.width=1;Y=c.getContext("2d");Y.imageSmoothingEnabled=!1;Yb=p("canvas");ha=!1;0>a.indexOf("\n")?te(a):je(a.split("\n"))};var je=function(a){var b,c,f;Eb=!0;e={};for(b=0;b<a.length;b++)2>a[b].length||(c=a[b].trim(),0==c.indexOf("#")||0>c.indexOf("=")||(c=c.split("="),f=c[0].trim().toLowerCase(),e[f]=c[1].trim()));ha=!1;null!=e.debug&&("true"==e.debug?(xb=window.open("","HAniSDebugInfo","scrollbars=yes,width=400,height=200"),ha=!0,K("HAniS Version 1.91")):
ha=!1);Hc=pb=null;null!=e.map_scale&&(Gc=Ta=!0,a=e.map_scale.split(","),pb=parseFloat(a[0]),Hc=1<a.length?parseFloat(a[1]):pb);Gd=" ";null!=e.distance_unit&&(Gd=e.distance_unit.trim());lb=" ";null!=e.divcan_style&&(lb=e.divcan_style.trim());b="blue";c="white";f="12px Arial";var d=null,r=10,Ba=10,g=10;Cd=1;Fd="white";null!=e.distance_display_style&&(a=e.distance_display_style.split(","),b=a[0].trim(),c=a[1].trim(),Fd=5<=a.length?a[4].trim():c,f=a[2].trim(),Cd=parseInt(a[3],10),5<a.length&&(d=a[5].trim(),
r=parseInt(a[6],10),Ba=parseInt(a[7],10),g=parseInt(a[8],10)));fe=new wb(b,c,f,d,r,Ba,g);b="black";c="white";f="12px Arial";d=null;g=Ba=r=10;null!=e.probe_display_style&&(a=e.probe_display_style.split(","),b=a[0].trim(),c=a[1].trim(),f=a[2].trim(),3<a.length&&(d=a[3].trim(),r=parseInt(a[4],10),Ba=parseInt(a[5],10),g=parseInt(a[6],10)));ge=new wb(b,c,f,d,r,Ba,g);null!=e.pause&&(md=parseInt(e.pause,10));null!=e.auto_refresh&&(ed=6E4*parseInt(e.auto_refresh,10),tb=setInterval("HAniS.reloadFOF();",ed),
lc=!0);null!=e.overlay_labels&&(U=e.overlay_labels.split(","));nb=!1;Ya=-1;null!=e.overlay_enhance&&(nb=!0,Ya=parseInt(e.overlay_enhance,10)-1);$a=null;Cb=!0;if(null!=e.overlay_allow_hoverzones)for(a=e.overlay_allow_hoverzones.split(","),$a=Array(a.length),b=0;b<a.length;b++)if($a[b]=!0,0==a[b].trim().toLowerCase().indexOf("n")||0==a[b].trim().toLowerCase().indexOf("f"))$a[b]=!1;xc=null;if(null!=e.overlay_spacer)for(a=e.overlay_spacer.split(","),xc=Array(a.length),b=0;b<a.length;b++)xc[b]=parseInt(a[b],
10);if(null!=e.overlay_probe_table)for(a=e.overlay_probe_table.split(","),b=0;b<a.length;b++)kc[b]=parseInt(a[b],10)-1;ma=null;if(null!=e.overlay_order)for(a=e.overlay_order.split(","),ma=Array(a.length),b=0;b<a.length;b++)ma[parseInt(a[b],10)-1]=b;$=null;if(null!=e.overlay_links)for(a=e.overlay_links.split(","),$=Array(a.length),b=0;b<a.length;b++)$[b]=parseInt(a[b],10);yb=null;if(null!=e.overlay_clear)for(a=e.overlay_clear.split(","),yb=Array(a.length),b=0;b<a.length;b++)yb[b]=a[b].trim().toLowerCase();
Xa=null;if(null!=e.overlay_transparent_amount)for(a=e.overlay_transparent_amount.split(","),Xa=Array(a.length),b=0;b<a.length;b++)Xa[b]=parseFloat(a[b])/100;jc=null;if(null!=U&&null!=e.overlay_zoom)for(a=e.overlay_zoom.split(","),jc=Array(a.length),b=0;b<a.length;b++)if(jc[b]=!0,0==a[b].trim().toLowerCase().indexOf("n")||0==a[b].trim().toLowerCase().indexOf("f"))jc[b]=!1;Ua=null;if(null!=U&&null!=e.overlay_preserve_list)for(a=e.overlay_preserve_list.split(","),Ua=Array(a.length),b=0;b<a.length;b++)if(Ua[b]=
!0,0==a[b].trim().toLowerCase().indexOf("n")||0==a[b].trim().toLowerCase().indexOf("f"))Ua[b]=!1;Ac=0;xd=" ";fb="white";dc="transparent";ec="14pt arial";yd=!1;null!=e.times_label_style&&(a=e.times_label_style.split(","),fb=a[0].trim(),1<a.length&&(Ac=Math.floor(60*parseFloat(a[1]))),1<a.length&&(Ac="?"==a[1].trim()||"auto"==a[1].trim().toLowerCase()?-Math.floor((new Date).getTimezoneOffset()):Math.floor(60*parseFloat(a[1]))),2<a.length&&(xd=a[2].trim()),3<a.length&&(dc=a[3].trim()),4<a.length&&(ec=
a[4].trim()),5<a.length&&-1!=a[5].trim().indexOf("t")&&(yd=!0));0==fb.indexOf("0x")&&(fb="#"+fb.substring(2));0==dc.indexOf("0x")&&(dc="#"+dc.substring(2));Jb=parseInt(ec,10);ce=new wb("black","white",ec,"black",20,5,5);zd=!1;null!=e.to_from_lock&&(a=e.to_from_lock.trim(),zd=0==a.indexOf("t")?!0:!1);b="black";c="white";f="14px arial";d=null;g=Ba=r=10;Ld=Md=" ";bd=Pb=null;null!=e.dirspd_display_style&&(a=e.dirspd_display_style.split(","),b=a[0].trim(),c=a[1].trim(),f=a[2].trim(),Ld=a[3],Md=a[4],5<
a.length&&(d=a[5].trim(),r=parseInt(a[6],10),Ba=parseInt(a[7],10),g=parseInt(a[8],10)),bd=new wb(b,c,f,d,r,Ba,g));b="black";c="white";f="14px arial";d=null;g=Ba=r=10;null!=e.tipbox_display_style&&(a=e.tipbox_display_style.split(","),b=a[0].trim(),c=a[1].trim(),f=a[2].trim(),3<a.length&&(d=a[3].trim(),r=parseInt(a[4],10),Ba=parseInt(a[5],10),g=parseInt(a[6],10)));Hd=new wb(b,c,f,d,r,Ba,g);J=null;if(null!=U&&null!=Ua)for(a=e.overlay_preserve.split(","),J=Array(Ua.length),b=f=0;b<Ua.length;b++)if(Ua[b]){J[b]=
Array(4);for(c=0;4>c;c++)J[b][c]=parseInt(a[f].trim(),10),f+=1;J[b][2]=J[b][2]-J[b][0]+1;J[b][3]=J[b][3]-J[b][1]+1}t=e.image_base;Ga=t=null!=t?t.trim():null;Eb=!0;if(null!=e.filenames){a=e.filenames.split(",");k=a.length;R=Array(k);for(b=0;b<k;b++)R[b]=null!=t?t+a[b].trim():a[b].trim();Eb=!1;G=0}if(null!=e.basename){a=e.basename;null!=t&&(a=t+e.basename);c=e.base_starting_number;null==c&&(c=0);k=e.num_frames;null==k&&(k=e.num_images);k=parseInt(k,10);R=Array(k);for(b=0;b<k;b++){f=b+parseInt(c,10);
if(0<=a.indexOf("*"))R[b]=a.replace("*",f);else if(0<=a.indexOf("?")){for(d=a;0<=d.lastIndexOf("?");)r=d.lastIndexOf("?"),d=d.substring(0,r)+f%10+d.substring(r+1),f=Math.floor(f/10);R[b]=d}else R[b]=a+b;K("image filename = "+R[b])}Eb=!1;G=0}Sc=!0;a=e.background_static;null==a||"f"!=a&&"false"!=a&&"n"!=a||(Sc=!1);if(null!=e.overlay_filenames){a=e.overlay_filenames.split(",");P=Array(k);for(b=0;b<a.length;b++)for(f=a[b].split("&"),G=a.length,c=0;c<k;c++)0==b&&(P[c]=Array(G)),P[c][b]=f[c].trim(),null!=
t&&(P[c][b]=(t+P[c][b]).trim());Eb=!1}Z=null;if(null!=e.image_preserve)for(a=e.image_preserve.split(","),Z=[],b=0;b<a.length;b++)Z[b]=parseInt(a[b].trim(),10),1<b%4&&(Z[b]=Z[b]-Z[b-2]+1);Ad=!0;null!=e.keep_zoom&&0==e.keep_zoom.trim().toLowerCase().indexOf("f")&&(Ad=!1);Qb=Ud=0;null!=e.hide_bottom&&(Ud=parseInt(e.hide_bottom.trim(),10));Nc=Vd=0;null!=e.hide_top&&(Vd=parseInt(e.hide_top.trim(),10));Id="<div>";Kd=300;Jd=500;null!=e.popup_style&&(a=e.popup_style,Id='<div style="'+e.popup_style+'">');
null!=e.popup_window_size&&(a=e.popup_window_size.split(","),Jd=a[0],Kd=a[1]);hb=!1;null!=e.active_zoom&&0==e.active_zoom.trim().toLowerCase().indexOf("t")&&(hb=!0);fc=1;null!=e.zoom_scale&&(fc=parseFloat(e.zoom_scale));gc=9999999;null!=e.maximum_zoom&&(gc=parseFloat(e.maximum_zoom));fd=!0;null!=e.use_progress_bar&&0==e.use_progress_bar.trim().toLowerCase().indexOf("f")&&(fd=!1);null!=e.dwell?(a=e.dwell.split(","),ba=parseInt(a[0].trim(),10),1<a.length&&(Ja=parseInt(a[1].trim(),10),10>Ja&&(Ja=10),
mb=parseInt(a[1].trim(),10),Qc=parseInt(a[1].trim(),10))):null!=e.rate&&(a=e.rate.split(","),ba=Math.round(1E4/parseFloat(a[0].trim())),1<a.length&&(Ja=Math.round(1E4/parseFloat(a[2].trim())),10>Ja&&(Ja=10),mb=Math.round(1E4/parseFloat(a[1].trim()))));eb=null;if(null!=e.times){a=e.times.split(",");eb=Array(a.length);for(b=0;b<a.length;b++)eb[b]=parseInt(a[b].trim(),10);ke(eb)}cc=null;null!=e.extrap_times_template&&(cc=RegExp(e.extrap_times_template));td=["Click on target's initial position","Click on target's final position",
"Move pointer around or click here to select target"];null!=e.extrap_prompts&&(td=e.extrap_prompts.split(","));if(null!=e.probe_table){a=new XMLHttpRequest;Fa=[];Rd=[];Mb=[];var z=" ";Nb=[];var Ha="Value=";rb=[];var n=1;sb=[];dd=[];xa=[];ya=[];za=[];var m,q=-1;h=-1;var l=0;a.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var c=a[b].replace(/\s+/g," ").trim().split(","),f=c[0].split(" ");if(0==f[0].indexOf("*"))h++,Fa[h]=[],Nb[h]=[],Mb[h]=[],rb[h]=
[],xa[h]=[],ya[h]=[],za[h]=[],dd[h]=[],sb[h]=[],q=-1,Rd[h]=1<c.length?c[1].trim():"None",l=1;else if(0!=l){q++;var d=Array(3);Fa[h][q]=parseFloat(f[0]);xa[h][q]=parseInt(f[1].trim(),10);ya[h][q]=parseInt(f[2].trim(),10);za[h][q]=parseInt(f[3].trim(),10);0!=q&&(d[0]=xa[h][q]-xa[h][q-1],d[1]=ya[h][q]-ya[h][q-1],d[2]=za[h][q]-za[h][q-1],m=0,Math.abs(d[1])>Math.abs(d[m])&&(m=1),Math.abs(d[2])>Math.abs(d[m])&&(m=2),dd[h][q-1]=m,sb[h][q-1]=d,0==sb[h][q-1][m]&&(sb[h][q-1][m]=1));1<c.length&&(0==c[1].trim().indexOf('"')?
(n=-1,c=c[1].trim(),Ha=c.substr(1,c.length-2),z=""):(n=parseInt(c[1],10),2<c.length&&(z=c[2].trim()),3<c.length&&(Ha=c[3].trim())));Nb[h][q]=Ha;rb[h][q]=n;Mb[h][q]=z}}};a.open("get",e.probe_table,!0);a.send()}pc=e.controls;K("controls = "+e.controls);K("bottom_controls = "+e.bottom_controls);Ea=Ic=db=cb=Gb=Fb=Ca=null;null!=pc&&le(pc,!0);qc=e.bottom_controls;null!=qc&&le(qc,!1);Eb?HAniS.getFOF():(Ub=!0,Wd())},te=function(a){var b=new XMLHttpRequest;b.onload=function(){je(this.responseText.split("\n"))};
b.open("get",a+"?"+Math.round(1E5*Math.random()),!0);b.send()},me=function(a){var b;if(null!=yb){for(b=0;b<yb.length;b++)-1!=yb[b].indexOf(a)&&(B[b].checked=!1);for(b=0;b<yb.length;b++)Xd(b)}},ke=function(a){var b=0;Xc=Array(a.length);for(var c=0;c<a.length;c++){var f=60*Math.floor(a[c]/100)+Math.floor(a[c])%100;0==c&&(ta=f);b=f-ta;0>b&&(b=f+1440-ta);Xc[c]=b;K("times s="+f+"  min="+Xc[c])}ta+=Ac;1440<=ta&&(ta-=1440);0>ta&&(ta+=1440);K("Starting minute = "+ta)},ne=function(a,b){if(0!=a)for(var c=0;c<
a;c++)B[ea[c].overlay].parentNode.style.visibility=b};this.reloadFOF=function(){K("reload FoF = "+tb);me("r");Eb?HAniS.newFOF(null!=Ga?Ga+Sd:Sd):(Ub=!0,Wd())};this.getFOF=function(){var a=e.file_of_filenames.trim();HAniS.newFOF(null!=Ga?Ga+a:a)};this.newFOF=function(a){var b,c,f,d,e,h=new XMLHttpRequest,g,z,Ha,n,m,q;pd=qa;var l=null;Wc=!1;Sb=pa;pa=!1;qa=k=0;R=[];D=null;La=0;F=null;Xb=0;Ma=Uc=!1;ra=null;$b=!1;W=-1;Db=Oa=ab=Na=null;qd=-1;P=[];var p=!1;if(null==eb||null!=cc)eb=[];K("new FOF="+a);ia&&
(null!=sa&&(sa.innerHTML=sa.label_on,T.style.cursor="default",pa=Sb,fa=-1),ia=!1,va());h.onload=function(){var a=this.responseText.split("\n");for(b=0;b<a.length;b++)if(!(2>a[b].length)&&(g=a[b].trim(),K("FOF: "+g),0!=g.indexOf("#")))if(0==g.indexOf("fof_extension"))m=g.split("="),l=m[1].trim();else if(0==g.indexOf("image_base"))m=g.split("="),t=m[1].trim();else if(0==g.indexOf("high_res_basemap")){m=g.split("=");q=m[1].split(",");ab=[];for(c=0;c<q.length;c++)ab[c]=q[c].trim(),null!=t&&(ab[c]=t+ab[c]);
$b=!0}else if(0==g.indexOf("high_res_overlay")){m=g.split("=");q=m[1].split(",");qd=parseInt(q[0].trim(),10)-1;Db=[];for(c=1;c<q.length;c++)Db[c-1]=q[c].trim(),null!=t&&(Db[c-1]=t+Db[c-1]);$b=!0}else if(0==g.indexOf("high_res_zoom")){m=g.split("=");q=m[1].split(",");ra=[];for(c=0;c<q.length;c++)ra[c]=parseFloat(q[c].trim());Yd()}else if(0==g.indexOf("hoverzone"))ue(g);else if(0==g.indexOf("hotzone"))oe(g);else if(0==g.indexOf("hotspot"))ve(g);else if(0==g.indexOf("map_scale"))m=g.split("="),q=m[1].split(","),
pb=parseFloat(q[0]),Hc=1<q.length?parseFloat(q[1]):pb;else if(0==g.indexOf("times")){m=g.split("=");q=m[1].split(",");for(b=0;b<q.length;b++)eb[b]=parseInt(q[b].trim(),10);p=!0}else{if(null!=cc){var h=g.match(cc);null!=h&&2==h.length?(eb.push(parseInt(h[1],10)),K("+ + + Extrap time = "+h[1]),p=!0):K("+ + + Cannot parse times using "+cc+" from line: "+g)}f=g.indexOf(" ");0>f&&(f=g.length);R[k]=g.substring(0,f).trim();null!=t&&(R[k]=t+R[k]);g=g.substring(f+1);d=g.indexOf('"');0<=d&&(null==Pa&&(Pa=[]),
f=g.substring(d+1),d=f.indexOf('"'),0<=d&&(Pa[k]=f.substring(0,d),0==k&&(bb.innerHTML=Pa[0])));P[k]=[];d=g.indexOf("overlay");if(0<=d)for(z=g.substring(d),d=z.indexOf("="),0>d&&K("Cannot find a = sign in "+z),Ha=z.substring(d+1),z=Ha.trim(),Ha=z.split(","),G=Ha.length,K("numOverlays set to "+G),e=0;e<Ha.length;e++)P[k][e]=Ha[e].trim(),null!=t&&(P[k][e]=(t+P[k][e]).trim());k+=1}p&&ke(eb);null!=l?(a=new XMLHttpRequest,a.onload=function(){var a=this.responseText.split("\n");for(b=0;b<a.length;b++)2>
a[b].length||(n=a[b].trim(),K("ext_FOF: "+n),0!=n.indexOf("#")&&0==n.indexOf("hotzone")&&oe(n));Zd()},a.onerror=function(){Zd()},a.open("get",l+"?"+Math.round(1E5*Math.random()),!0),a.send()):Zd()};Sd=a;h.open("get",a+"?"+Math.round(1E5*Math.random()),!0);h.send()};var Zd=function(){0!=qa?ne(qa,"visible"):0!=pd&&ne(pd,"hidden");Ub=!0;Wd()},Wd=function(){var a,b,c,f="?"+Math.round(1E4*Math.random());S=Array(k);ub=Aa=0;Td=fd;Bd&&(Sa.max=k-1);rc&&(Ab||nb)&&(Ka=[],da=[],ob=[],Rc=[],sc=[]);null!=ca&&(ca.selectedIndex=
0);for(a=0;a<k;a++){rc&&(Ab||nb)&&(Ka[a]=p("canvas"),da[a]=p("canvas"));S[a]=new Image;S[a].gotit=!1;S[a].frameNum=a;S[a].onerror=function(){Aa++};S[a].onload=function(){rc&&(rc=!1,H=this.height,aa=this.width,l.height=H,l.width=aa,L.height=H,L.width=aa,Lc=aa/2-100,Mc=H/2-10,X.setAttribute("style",lb+"position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;height:"+H+"px;width:"+
aa+"px;"));if(0<Xb&&!Uc){Yb.height=L.height;Yb.width=L.width;Zb=Yb.getContext("2d");Zb.clearRect(0,0,Yb.width,Yb.height);for(var a=0;a<F.length;a++){for(var e=F[a].ctx.getImageData(0,0,F[a].width,F[a].height).data,g=Zb.getImageData(F[a].xmin,F[a].ymin,F[a].width,F[a].height),h=3;h<e.length;h+=4)0!=e[h]&&(g.data[h]=a+1);Zb.putImageData(g,F[a].xmin,F[a].ymin)}hb||(Ma=!0);Uc=!0}if(Ub){Ub=!1;s=l.getContext("2d");s.imageSmoothingEnabled=!1;s.fillStyle="blue";s.font="bold 20px Arial";d=L.getContext("2d");
d.imageSmoothingEnabled=!1;Wb=Array(k);vc&&we(k);if(0<G)for(C=Array(k),c=0;c<k;c++)for(C[c]=Array(G),b=0;b<G;b++)C[c][b]=new Image,C[c][b].gotit=!1,C[c][b].frameNum=c,C[c][b].overlayNum=b,C[c][b].onerror=function(){Aa++},C[c][b].onload=function(){this.gotit=!0;Aa++;Pc();if(this.height!=l.height||this.width!=l.width)this.gotit=!1,K("Bad image size:"+this.src);if(nb&&this.gotit&&this.overlayNum==Ya){var a=this.frameNum;Ka[a].height=this.height;Ka[a].width=this.width;Vb=Ka[a].getContext("2d");Vb.drawImage(this,
0,0);Rc[a]=Vb.getImageData(0,0,this.width,this.height).data;da[a].height=this.height;da[a].width=this.width;ob[a]=da[a].getContext("2d");ob[a].drawImage(this,0,0);sc[a]=ob[a].getImageData(0,0,this.width,this.height);C[a][this.overlayNum]=null;C[a][this.overlayNum]=da[a];C[a][this.overlayNum].gotit=!0}},a=P[c][b],void 0==Rb||Rb[b]||(a=P[c][b]+f),C[c][b].src=a,ub++;if(null!=ab)for(Na=[],b=0;b<ab.length;b++)Na[b]=new Image,Na[b].gotit=!1,Na[b].onerror=function(a){Aa++},Na[b].onload=function(a){a.currentTarget.gotit=
!0;Aa++;Pc()},Na[b].src=ab[b],ub++;if(null!=Db)for(Oa=[],b=0;b<ab.length;b++)Oa[b]=new Image,Oa[b].gotit=!1,Oa[b].onerror=function(a){Aa++},Oa[b].onload=function(a){a.currentTarget.gotit=!0;Aa++;Pc()},Oa[b].src=Db[b],ub++}this.height==l.height&&this.width==l.width?this.gotit=!0:(this.gotit=!1,K("Image has invalid size:"+this.src));Ab&&this.gotit&&(a=this.frameNum,Ka[a].height=this.height,Ka[a].width=this.width,Vb=Ka[a].getContext("2d"),Vb.drawImage(this,0,0),Rc[a]=Vb.getImageData(0,0,this.width,this.height).data,
da[a].height=this.height,da[a].width=this.width,ob[a]=da[a].getContext("2d"),ob[a].drawImage(this,0,0),sc[a]=ob[a].getImageData(0,0,this.width,this.height),S[a]=null,S[a]=da[a],S[a].gotit=!0);Aa++;Pc();ae||(ae=!0,jb(!0),pe());pa=Sb;Ad||HAniS.resetZoom();Wc=!0};var e=R[a];Sc||(e=R[a]+f);S[a].src=e;ub++}Kb=Ia=!1;va()},vb=function(a,b,c,f,d){a.label_on=c;a.label_off=f;c=null;f=e[b+"_labels"];null==f&&(f=e[b+"_label"]);null!=f&&(f=f.split(","),a.label_on=f[0].trim(),1<f.length&&(a.label_off=f[1].trim()),
2<f.length&&(c="width:"+f[2].trim()+"px;"));null!=d&&(a.title=d);a.innerHTML=a.label_on;b=(null!=c?c:"")+Wa+e[b+"_style"];null!=b&&a.setAttribute("style",b)},le=function(a,b){var c,f,d,r=p("div");r.align="center";r.setAttribute("style","position:relative;padding:2px;width:100%;");Wa=e.buttons_style;var l=null,g=null;b?(null!=e.controls_style&&r.setAttribute("style",e.controls_style),l=e.controls_tooltip,T.insertBefore(r,X)):(null!=e.bottom_controls_style?r.setAttribute("style",e.bottom_controls_style):
null!=e.controls_style&&r.setAttribute("style",e.controls_style),l=e.bottom_controls_tooltip,T.appendChild(r));null!=l&&(d=l.split(","));var z=a.split(","),s=null,n;for(c=0;c<z.length;c++){n=null!=l?d[c]:null;var m=e.enhance_filename;null==m&&(m=e.enhance_table);if("enhance"==z[c].trim()&&null!=m){ca=p("select");g=e.enhance_style;null!=g&&ca.setAttribute("style",g);null!=n&&(ca.title=n);g=p("option");g.innerHTML="Pick Enhancement";g.value=-1;ca.add(g);ca.addEventListener("change",HAniS.doEnhance,
!1);Ab=!nb;ca.disabled=Ab?!1:!0;r.appendChild(ca);g=new XMLHttpRequest;Fa=[];Mb=[];Nb=[];rb=[];var q,u,v;xa=[];ya=[];za=[];Kc=[];h=-1;var x=!1,t,A,y,C,G,D,L,F,N,I,O,K,P;g.onload=function(){for(var a=this.responseText.split("\n"),b=0;b<a.length;b++)if(!(2>a[b].length)){var c=a[b].replace(/\s+/g," ").trim(),d=c.indexOf("#");if(0!=d)if(0<d&&(c=c.substring(0,d)),0==c.indexOf("*"))h++,Fa[h]=Array(256),Nb[h]=Array(256),Mb[h]=Array(256),rb[h]=Array(256),xa[h]=Array(256),ya[h]=Array(256),za[h]=Array(256),
Kc[h]=Array(256),Fa[h]=Array(256),q=" ",u="Value =",v=1,d=p("option"),d.innerHTML=c.substring(1),d.value=h,ca.add(d);else{var f=c.indexOf("value");0>f&&(f=c.indexOf("probe"));x=!1;I=O=0;0<f&&(d=c.substring(f+1),c=c.substring(0,f),f=d.indexOf("="),d=d.substring(f+1),d=d.split(","),1==d.length?(u=d[0].trim(),v=-1,x=!1):(I=parseFloat(d[0].trim()),O=parseFloat(d[1].trim()),2<d.length&&(v=parseInt(d[2],10)),3<d.length&&(q=d[3].trim()),4<d.length&&(u=d[4].trim()),x=!0));c=c.split(" ");t=parseInt(c[0].trim(),
10);A=parseInt(c[1].trim(),10);y=A-t;C=parseFloat(c[2].trim());G=parseFloat(c[3].trim());D=parseFloat(c[4].trim());L=parseFloat(c[5].trim());F=parseFloat(c[6].trim());N=parseFloat(c[7].trim());K=P=255;9<c.length&&(K=parseFloat(c[8].trim()),P=parseFloat(c[9].trim()));for(c=t;c<=A;c++)0==y?(xa[h][t]=C,ya[h][t]=D,za[h][t]=F,Kc[h][t]=K):(xa[h][c]=Math.round(C+(G-C)*(c-t)/y),ya[h][c]=Math.round(D+(L-D)*(c-t)/y),za[h][c]=Math.round(F+(N-F)*(c-t)/y),Kc[h][c]=Math.round(K+(P-K)*(c-t)/y)),Nb[h][c]=u,Mb[h][c]=
q,rb[h][c]=v,x&&(Fa[h][c]=I+(O-I)*(c-t)/y)}}};g.open("get",m,!0);g.send()}"startstop"==z[c].trim()&&(Ca=p("button"),vb(Ca,"startstop","Start","Stop",n),Ca.addEventListener("click",HAniS.toggleIsLooping,!1),r.appendChild(Ca));"looprock"==z[c].trim()&&(Ra=p("button"),vb(Ra,"looprock","Rock","Loop",n),zb=1,Ra.addEventListener("click",HAniS.toggleLoopRock,!1),r.appendChild(Ra));"extrap"==z[c].trim()&&(sa=p("button"),vb(sa,"extrap","Enable Extrap","Disable Extrap",n),sa.addEventListener("click",HAniS.toggleExtrap,
!1),r.appendChild(sa));"distance"==z[c].trim()&&(ua=p("button"),vb(ua,"distance","Show dist","Hide dist",n),Ta=Gc=!1,ua.addEventListener("click",function(){Ta=!Ta;ua.innerHTML=Ta?ua.label_off:ua.label_on},!1),r.appendChild(ua));"probe"==z[c].trim()&&(qb=p("button"),vb(qb,"probe","Show probe","Hide probe",n),Lb=ad=!1,qb.addEventListener("click",function(){(ad=!ad)?(qb.innerHTML=qb.label_off,Lb=!0):(qb.innerHTML=qb.label_on,Lb=!1)},!1),r.appendChild(qb));"refresh"==z[c].trim()&&(Ic=p("button"),vb(Ic,
"refresh","Refresh",null,n),Ic.addEventListener("click",HAniS.reloadFOF,!1),r.appendChild(Ic));"setframe"==z[c].trim()&&(Sa=p("input"),Sa.type="range",Sa.min=0,Sa.max=99,Sa.value=0,$c="Frame #*",null!=e.setframe_label&&($c=e.setframe_label),Dc=p("span"),Dc.innerHTML=$c.replace("*",1),g="display:block;vertical-align:middle;"+e.setframe_style,Sa.setAttribute("style",g),m=p("span"),m.setAttribute("style","display:inline-block;vertical-align:top;"),Dc.setAttribute("style","display:block;vertical-align:middle;"+
e.setframe_label_style),m.appendChild(Dc),m.appendChild(Sa),r.appendChild(m),Sa.addEventListener("input",function(a){jb(!1);mc(parseInt(Sa.value,10));Dc.innerHTML=$c.replace("*",w+1);ja()},!1),Bd=!0);"framelabel"==z[c].trim()&&(bb=p("button"),bb.innerHTML="",Pa=null,null!=e.frame_labels&&(Pa=e.frame_labels.split(","),bb.innerHTML=Pa[0]),g=Wa+e.framelabel_style,null!=g&&bb.setAttribute("style",g),r.appendChild(bb));if("autorefresh"==z[c].trim()||"autorefresh/off"==z[c].trim())null!=tb&&clearInterval(tb),
Ea=p("button"),vb(Ea,"autorefresh","Disable Auto Refresh","Enable Auto Refresh",n),Ea.addEventListener("click",HAniS.toggleAutoRefresh,!1),lc=!1,r.appendChild(Ea),"autorefresh"==z[c].trim()?HAniS.toggleAutoRefresh():Ea.innerHTML=Ea.label_off;"step"==z[c].trim()&&(m=e.step_labels,m=null!=m?m.split(","):["<",">"],Gb=p("button"),Gb.innerHTML=m[0],Gb.addEventListener("click",function(){jb(!1);Oc(-1);ja()},!1),g=Wa+e.step_style,null!=g&&Gb.setAttribute("style",g),null!=l&&(Gb.title=d[c].trim()),r.appendChild(Gb),
Fb=p("button"),Fb.innerHTML=m[1],Fb.addEventListener("click",function(){jb(!1);Oc(1);ja()},!1),null!=g&&Fb.setAttribute("style",g),null!=l&&(Fb.title=d[c].trim()),r.appendChild(Fb));"firstlast"==z[c].trim()&&(m=e.firstlast_labels,m=null!=m?m.split(","):["<<",">>"],kb=p("button"),kb.innerHTML=m[0],kb.addEventListener("click",function(){jb(!1);mc(0);ja()},!1),g=Wa+e.firstlast_style,null!=g&&kb.setAttribute("style",g),null!=l&&(kb.title=d[c].trim()),r.appendChild(kb),ka=p("button"),ka.innerHTML=m[1],
ka.addEventListener("click",function(){jb(!1);mc(k-1);ja()},!1),null!=g&&ka.setAttribute("style",g),null!=l&&(ka.title=d[c].trim()),r.appendChild(ka));"setspeed"==z[c].trim()?(Qa=p("input"),Qa.type="range",Qa.min=Ja,Qa.max=mb,Qa.value=mb-ba,null!=l&&(Qa.title=d[c].trim()),g="vertical-align:middle;"+e.setspeed_style,Qa.setAttribute("style",g),Qa.addEventListener("input",function(a){ba=mb-parseInt(Qa.value,10)+30;jb(!0);ja()},!1),r.appendChild(Qa)):"speed"==z[c].trim()&&(m=e.speed_labels,m=null!=m?
m.split(","):["-","+"],db=p("button"),db.innerHTML=m[0],db.addEventListener("click",function(){ba+=Qc;cb.disabled=!1;ba>mb&&(ba=mb,db.disabled=!0)},!1),g=Wa+e.speed_style,null!=g&&db.setAttribute("style",g),null!=l&&(db.title=d[c].trim()),r.appendChild(db),cb=p("button"),cb.innerHTML=m[1],cb.addEventListener("click",function(){ba-=Qc;db.disabled=!1;ba<Ja&&(ba=Ja,cb.disabled=!0)},!1),null!=g&&cb.setAttribute("style",g),null!=l&&(cb.title=d[c].trim()),r.appendChild(cb));"zoom"==z[c].trim()&&(gb=p("button"),
vb(gb,"zoom","Zoom","Un-zoom",n),gb.addEventListener("click",HAniS.toggleZooming,!1),r.appendChild(gb));"toggle"==z[c].trim()&&(Wb=[],n=e.toggle_size,null!=n?(n=n.split(","),Bb=parseInt(n[0],10),tc=parseInt(n[1],10),uc=parseInt(n[2],10)):(tc=Bb=10,uc=3),Za=p("div"),Za.setAttribute("style","position:relative;border:0px;margin:0px;padding:0px;-webkit-user-select:none; -moz-user-select:none; -ms-user-select:none; user-select:none; -webkit-tap-heightlight-color:transparent;"),Za.style.backgroundColor=
r.style.backgroundColor,Za.align="center",od=new PEvs(Za,null,null,null,null,HAniS.togclick,null),wc=p("canvas"),wc.height=2*tc,rd=wc.getContext("2d"),Za.appendChild(wc),b?T.insertBefore(Za,X):T.appendChild(Za),vc=!0,null!=l&&(Za.title=d[c].trim()));if("overlay"==z[c].trim()){B=[];m=e.overlay_tooltip;n=null;null!=m&&(n=m.split(","));m=e.overlay_radio;g=null;null!=m&&(g=m.split(","));var E=e.overlay_labels_color,R=null;null!=E&&(R=E.split(","));Rb=[];f=e.overlay_caching;E=null;null==f&&(f=e.overlay_static);
null!=f&&(E=f.split(","));for(f=0;f<U.length;f++){var M=U[f].trim();if(0==f||0==M.indexOf("/"))0==M.indexOf("/")&&(M=M.substr(1)),s=p("div"),s.align="center",b?T.insertBefore(s,X):T.appendChild(s),null!=e.overlay_labels_style&&s.setAttribute("style",e.overlay_labels_style);var J=!1,S=M.length;0<M.indexOf("/on")&&M.indexOf("/on")==S-3&&(J=!0,M=M.substr(0,S-3));var H=!1;0<M.indexOf("/always")&&M.indexOf("/always")==S-7&&(H=J=!0);var Q=!1;0<M.indexOf("/hidden")&&M.indexOf("/hidden")==S-7&&(Q=!0);null!=
E?"y"==E[f].trim().toLowerCase()||"t"==E[f].trim().toLowerCase()?Rb[f]=!0:Rb[f]=!1:Rb[f]=!0;B[f]=p("input");B[f].type="checkbox";B[f].value=M;null!=e.checkbox_style&&B[f].setAttribute("style",e.checkbox_style);B[f].checked=J;null!=ca&&f==Ya&&B[f].checked&&(ca.disabled=!1);null!=$a&&!$a[f]&&J&&(Cb=!1);B[f].addEventListener("click",HAniS.overClick,!1);null!=m&&-1!=g[f].indexOf("true")&&(B[f].type="radio",J=g[f].indexOf("/"),B[f].name=-1!=J?g[f].substr(J+1).trim():"all");H||Q||(null!=n&&(B[f].title=
n[f]),H=p("label"),H.htmlFor=M,null!=n&&(H.title=n[f]),H.appendChild(document.createTextNode(M)),M="vertical-align:top;",null!=R&&(M=M+"color:"+R[f]+";"),H.setAttribute("style",M),M=p("span"),Q="10",null!=xc&&(Q=10+xc[f]),M.setAttribute("style","margin-left:"+Q+"px;"),M.appendChild(B[f]),M.appendChild(H),s.appendChild(M))}if(null==$)for($=Array(U.length),f=0;f<U.length;f++)$[f]=0;else for(f=0;f<U.length;f++)Xd(f)}}},Xd=function(a){var b,c;if(0>$[a]){c=!1;for(b=0;b<U.length;b++)$[b]!=-$[a]||c||(c=
B[b].checked);B[a].checked=c}},ve=function(a){0==La&&(D=[]);a=a.split("=")[1].split(",");var b=a[4].trim(),c=a[4].indexOf("/"),d=-1;-1!=c&&(d=parseInt(a[4].substring(c+1),10)-1,b=b.substring(0,c));D[La]=new hd(parseInt(a[0].trim(),10),parseInt(a[1].trim(),10),a[2].trim(),a[3].trim(),b.toLowerCase(),a[5].trim().toLowerCase(),a[6].trim(),d,8==a.length?a[7].trim():null);La+=1},ue=function(a){0==Xb&&(F=[],V=-1);var b=a.split("=")[1].split("(");a=b[0].split(",");var c=a[0].trim();0==c.indexOf("0x")&&(c=
"#"+c.substring(2));F[Xb]=new ga(c,a[1].trim(),a[2].trim(),a[3].trim(),b[1].trim());Xb+=1},oe=function(a){0==qa&&(ea=[]);a=a.split("=")[1].split(",");ea[qa]=new gd(parseInt(a[0],10)-1,parseInt(a[1],16),a[2].trim(),a[3].trim(),5==a.length?a[4].trim():"Click for details");qa+=1};this.drag=function(a){u=y.getX();v=y.getY();Kb=Ia=!1;Ta&&(!Gc||Gc&&a.shiftKey)?(hc=u,ic=v,Kb=!0):(hb&&I!=Bc?(Q=Math.round(na*N-u)/N,E=Math.round(oa*I-v)/I,0>Q&&(Q=0),E<Nc&&(E=Nc),Q+aa>l.width&&(Q=l.width-aa),E+H>l.height-Qb&&
(E=l.height-Qb-H),na=Math.round(Q+u/N),oa=Math.round(E+v/I)):!ia&&Ma&&(V=-1,Cb&&0<=u&&0<=v&&(A=Zb.getImageData(u,v,1,1).data,0!=A[3]&&(V=A[3]-1))),Cc=!0,ja());va()};var Yd=function(){if($b){W=-1;for(var a=0;a<ra.length;a++)N>=ra[a]&&(W=a)}},$d=function(a,b){"popup"==a.action?(null!=la&&la.close(),la=window.open("","HAniSPopup","scrollbars=yes,width="+Jd+",height="+Kd),la.document.write(Id+a.value+"</div>")):"link"==a.action?window.open(a.value,"_blank",""):"fof"==a.action&&(t=Ga,HAniS.resetZoom(),
HAniS.newFOF(a.value),me(b))};this.resetZoom=function(){N=Zc;I=Bc;null!=gb&&(gb.innerHTML=gb.label_on,hb=!1);na=u;oa=v;E=Q=0;H=l.height;aa=l.width;Yd();ja();Uc&&(Ma=!0)};this.canTip=function(){var a;Ia=!1;u=y.getX();v=y.getY();if(!(ia&&v<ud&&u>sd)){na=Math.round(Q+u/N);oa=Math.round(E+v/I);if(0!=qa)for(a=0;a<qa;a++)if(ea[a].overlay>=G)K(" Error...hotzone overlay # "+ea[a].overlay+" > number of overlays = "+G);else if(B[ea[a].overlay].checked&&(Y.clearRect(0,0,1,1),Y.drawImage(C[w][ea[a].overlay],
Math.floor(na),Math.floor(oa),1,1,0,0,1,1),A=Y.getImageData(0,0,1,1).data,Tc=(A[0]<<16)+(A[1]<<8)+A[2],Tc==ea[a].color)){Ia=!0;kd=u;ld=v;jd=ea[a].tip;break}if(0!=La)for(a=0;a<La;a++)if((-1==D[a].overlay||B[D[a].overlay].checked)&&u>D[a].x0&&u<D[a].x1&&v>D[a].y0&&v<D[a].y1&&null!=D[a].tip){Ia=!0;kd=u;ld=v;jd=D[a].tip;break}va()}};this.move=function(){if(!ia&&Ma&&(V=-1,Cb)){var a=y.getX(),b=y.getY();0<=a&&0<=b&&(A=Zb.getImageData(a,b,1,1).data,0!=A[3]&&(V=A[3]-1))}ia&&2<=fa&&(u=y.getX(),v=y.getY());
va()};this.down=function(){Ia&&(Ia=!1,va());u=y.getX();v=y.getY();Ec=u;Fc=v;hc=Ec;ic=Fc;na=Math.round(Q+u/N);oa=Math.round(E+v/I);Cc=!1};this.up=function(a){Ia=!1;if(ia){u=y.getX();v=y.getY();if(3>fa)if(Da[fa]=u,wa[fa]=v,Hb[fa]=Xc[w],0==fa)fa=1,mc(k-1),zc=1,Pb=null;else{vd=Hb[1]-Hb[0];yc=(Da[1]-Da[0])/vd;bc=(wa[1]-wa[0])/vd;if(null!=bd&&null!=pb){var b=yc*pb,c=bc*Hc,d=Math.round(60*Math.sqrt(b*b+c*c)),b=Math.atan2(b,-c)/.0174533;0>b&&(b+=360);Pb=Ld+re[Math.round(b/22.5)]+" at "+d+" "+Md;he=Da[0];
ie=0<bc?wa[0]-15:wa[0]+30}d=parseInt(ec,10);x=Math.round(Math.abs(4*(d+4)/yc));Ib=Math.round(Math.abs(2*(d+4)/bc));Ib<x&&(x=Ib);120<x?x=120*Math.floor(x/120)+60:90<x?x=120:60<x?x=90:30<x?x=60:15<x?x=30:10<x?x=15:5<x?x=10:2<x?x=5:0==x&&(x=1);Ib=Hb[1]/x*x+x;ac=1;zd&&(ac=-1);wd=yc*x;Yc=bc*x;mc(k-1);fa=3;zc=2}else if(v<ud&&u>sd&&3==fa){qe();va();return}va()}if(Kb)Kb=!1,va();else if(null!=ua&&hb&&(Ta=!1,ua.innerHTML=ua.label_on),Cc)Cc=!1;else if(a.altKey)HAniS.resetZoom();else if(Ma&&0<=V&&Vc)$d(F[V],
"z");else{u=y.getX();v=y.getY();if(0!=qa)for(d=0;d<qa;d++)if(ea[d].overlay>=G)K(" Error...hotzone overlay # "+ea[d].overlay+" > number of overlays = "+G);else if(B[ea[d].overlay].checked&&(Y.clearRect(0,0,1,1),Y.drawImage(C[w][ea[d].overlay],Math.floor(na),Math.floor(oa),1,1,0,0,1,1),A=Y.getImageData(0,0,1,1).data,Tc=(A[0]<<16)+(A[1]<<8)+A[2],Tc==ea[d].color)){$d(ea[d],"z");return}if(0!=La)for(d=0;d<La;d++)if((-1==D[d].overlay||B[D[d].overlay].checked)&&u>D[d].x0&&u<D[d].x1&&v>D[d].y0&&v<D[d].y1){$d(D[d],
"s");return}hb&&(Ma=!1,a.ctrlKey?(N-=.1*fc,I-=.1*fc):(N+=.1*fc,I+=.1*fc,N>gc&&(N=gc),I>gc&&(I=gc)),N<Zc||I<Bc?(N=Zc,I=Bc,na=u,oa=v,E=Q=0,H=l.height,aa=l.width,Nc=Qb=0):(Q=Math.round(na*N-u)/N,E=Math.round(oa*I-v)/I,H=Math.floor(l.height/I),E+H>l.height-Qb&&(E=l.height-Qb-H),aa=Math.floor(l.width/N),Qb=Ud,Nc=Vd),Yd());ja();va()}};this.toggleAutoRefresh=function(){lc?(Ea.innerHTML=Ea.label_off,null!=tb&&clearInterval(tb),lc=!1):(Ea.innerHTML=Ea.label_on,tb=setInterval("HAniS.reloadFOF();",ed),lc=!0)};
this.toggleLoopRock=function(){Tb?(null!=Ra&&(Ra.innerHTML=Ra.label_on),Tb=!1):(null!=Ra&&(Ra.innerHTML=Ra.label_off),Tb=!0)};this.toggleExtrap=function(){ia?(null!=sa&&(sa.innerHTML=sa.label_on,T.style.cursor="default",pa=Sb,fa=-1),ia=!1,va()):(null!=sa&&(ia=!0,Pb=null,T.style.cursor="crosshair",sa.innerHTML=sa.label_off,Sb=pa,pa=!1,HAniS.resetZoom(),qe(),va()),ja())};var qe=function(){zc=0;Da=Array(2);wa=Array(2);Hb=Array(2);fa=0;Pb=null;mc(0)},jb=function(a){pa=!a;HAniS.toggleIsLooping()};this.doEnhance=
function(a){if(Ab||nb){var b=da[0].height,c=da[0].width;a=parseInt(ca.value,10);var d,e,h,l;0<=a&&(d=xa[a],e=ya[a],h=za[a],l=Kc[a],kc[Ya]=a);for(var c=b*c*4,g=0;g<Ka.length;g++)if(da[g].gotit){da[g].gotit=!1;var k=sc[g].data,p=Rc[g];if(0>a)for(var n=0;n<c;n+=4)k[n]=p[n],k[n+1]=p[n+1],k[n+2]=p[n+2],k[n+3]=p[n+3];else for(n=0;n<c;n+=4)b=p[n],b===p[n+1]&&b===p[n+2]&&(k[n]=d[b],k[n+1]=e[b],k[n+2]=h[b],k[n+3]=l[b]);ob[g].putImageData(sc[g],0,0);da[g].gotit=!0}}};this.overClick=function(a){var b;Cb=!0;
for(b=0;b<$.length;b++)a.target!=B[b]&&Xd(b),null!=$a&&!$a[b]&&B[b].checked&&(Cb=!1),null!=ca&&b==Ya&&(ca.disabled=!B[b].checked);ja()};this.toggleIsLooping=function(){pa?(pa=!1,null!=Ca&&(Ca.innerHTML=Ca.label_on)):(pa=!0,null!=Ca&&(Ca.innerHTML=Ca.label_off))};this.toggleZooming=function(){hb?HAniS.resetZoom():(gb.innerHTML=gb.label_off,hb=!0,null!=ua&&(Ta=!1,ua.innerHTML=ua.label_on),Ma=!1,ia&&HAniS.toggleExtrap())};var nc=function(a,b){Wb[a]=b;if(vc){var c=nd+a*(Bb+uc),d="orange";0==b?d="blue":
-1==b&&(d="red");rd.fillStyle=d;rd.fillRect(c,tc/2,Bb,tc)}};this.togclick=function(a){var b=od.getX();od.getY();var c=nd;for(a=0;a<Wb.length;a++){if(b>c&&b<c+Bb){b=0;0<=Wb[a]&&(b=-1);nc(a,b);break}c=c+Bb+uc}};var we=function(a){vc&&(wc.width=l.width,nd=l.width/2-a*(Bb+uc)/2);for(var b=0;b<a;b++)nc(b,0)},mc=function(a){nc(w,0);w=a;nc(w,1)},Oc=function(a){nc(w,0);do 0<a?(w+=1,w>=k&&(Tb?(w=k-1,zb=-zb):w=0)):(w-=1,0>w&&(Tb?(w=0,zb=-zb):w=k-1));while(0>Wb[w]);nc(w,1);null!=bb&&null!=Pa&&null!=Pa[w]&&(bb.innerHTML=
Pa[w])},oc=function(a,b,c,e,h){d.globalAlpha=1;d.font=a.font;var k=a.fontHeight;c=c-k-6;var l=d.measureText(e).width;1==h&&(b-=l);0==h&&(b-=l/2);5>b&&(b=5);5>c&&(c=5);c+k+3>L.height&&(c=L.height-k-6);b+3+l>L.width&&(b=L.width-l-6);d.save();d.beginPath();d.fillStyle=a.bg;null!=a.scolor&&(d.shadowColor=a.scolor,d.shadowBlur=a.sblur,d.shadowOffsetX=a.sxoff,d.shadowOffsetY=a.syoff);Dd=b-3;de=c;ee=l+6;Ed=k+6;d.fillRect(Dd,de,ee,Ed);d.closePath();d.restore();d.textBaseline="bottom";d.fillStyle=a.fg;d.fillText(e,
b,c+k+3)},va=function(){d.clearRect(0,0,L.width,L.height);Vc=!1;if(ia){d.beginPath();d.lineWidth=2;d.strokeStyle="white";var a=fa;1<a&&(a=2);for(var b=0;b<a;b++)1<fa&&(d.moveTo(Da[0],wa[0]),d.lineTo(Da[1],wa[1])),d.moveTo(Da[b]-15,wa[b]),d.lineTo(Da[b]+15,wa[b]),d.moveTo(Da[b],wa[b]-15),d.lineTo(Da[b],wa[b]+15);d.closePath();d.stroke();if(3==fa){var c=u,e=v;d.moveTo(c,e);d.fillStyle=fb;d.fillRect(c-2,e-2,5,5);for(var b=Ib,a=Math.round(c+ac*yc*(Ib-Hb[1])),h=Math.round(e+ac*bc*(Ib-Hb[1])),k=0;300>k;k++){d.beginPath();
d.lineWidth=1;d.strokeStyle=fb;d.moveTo(c,e);d.lineTo(a,h);d.stroke();d.beginPath();d.lineWidth=3;d.rect(a-2,h-2,5,5);d.stroke();if(3>a||a+3>L.width||3>h||h+3>L.height)break;e=ta+b;e=100*Math.floor(e/60)+e%60;e%=2400;yd?(c="AM",1200<=e?(1300<=e&&(e-=1200),c="PM"):100>e&&(e+=1200),c=Math.floor(e/100)+":"+Math.floor(Math.floor(e%100)/10)+Math.floor(e%10)+" "+c):(c=e+" ",1E3>e&&(c="0"+e),100>e&&(c="00"+e),10>e&&(c="000"+e));e=0;Math.abs(Yc)<Jb+5&&(e=45*.0174533);var l=h;0>wd*Yc&&0==e&&(l=h+Jb);d.font=
ec;var c=c+" "+xd,g=d.measureText(c).width;d.fillStyle=dc;0===e?(d.fillRect(a+2,l-Jb-2+e,g+4,Jb+3),d.fillStyle=fb,d.textBaseline="bottom",d.fillText(c,a+5,l)):(d.save(),d.translate(a+5,h),d.rotate(e),d.fillRect(2,-2,g+4,Jb+3),d.fillStyle=fb,d.textBaseline="bottom",d.fillText(c,5,Jb),d.restore());c=a;e=h;a=Math.round(c+ac*wd);h=Math.round(e+ac*Yc);b+=x}}null!=Pb&&oc(bd,he,ie,Pb,0);oc(ce,999,10,td[zc],0);sd=Dd;ud=Ed}Kb&&(b=pb*(Ec-hc)/N,a=Hc*(Fc-ic)/I,b=" "+Math.sqrt(b*b+a*a).toFixed(Cd)+" "+Gd+" ",
oc(fe,hc,ic,b,-1),d.beginPath(),d.strokeStyle=Fd,d.lineWidth=3,d.moveTo(Ec,Fc),d.lineTo(hc,ic),d.stroke(),d.closePath());Ia&&oc(Hd,kd,ld,jd,-1);if(Lb&&(u=y.getX(),v=y.getY(),0<=u&&0<=v))for(na=Math.round(Q+u/N),oa=Math.round(E+v/I),a=0;a<G;a++)if(C[w][a].gotit&&B[a].checked&&(a==Ya||null!=kc[a]&&0<=kc[a])){Y.clearRect(0,0,1,1);a==Ya?Y.drawImage(Ka[w],na,oa,1,1,0,0,1,1):Y.drawImage(C[w][a],na,oa,1,1,0,0,1,1);A=Y.getImageData(0,0,1,1).data;Jc=999;O=kc[a];h="Undefined";if(0==A[3])h=Rd[O];else{if(a==
Ya)Nd=0,ib=A[0],Jc=0;else for(b=0;b<Fa[O].length-1;b++)Va[0]=A[0]-xa[O][b],0>Va[0]*(xa[O][b+1]-A[0]-1)||(Va[1]=A[1]-ya[O][b],0>Va[1]*(ya[O][b+1]-A[1]-1)||(Va[2]=A[2]-za[O][b],0>Va[2]*(za[O][b+1]-A[2]-1)||(Ob=dd[O][b],cd=Va[Ob]/sb[O][b][Ob],Qd=Math.abs(Va[Od[Ob]]-cd*sb[O][b][Od[Ob]])+Math.abs(Va[Pd[Ob]]-cd*sb[O][b][Pd[Ob]]),Qd<Jc&&(ib=b,Jc=Qd,Nd=cd))));999>Jc?(h=Nb[O][ib],-1!=rb[O][ib]&&(h=h+" "+(Fa[O][ib]+Nd*(Fa[O][ib+1]-Fa[O][ib])).toFixed(rb[O][ib])+" "+Mb[O][ib])):K("RGB err: R="+A[0]+" G="+A[1]+
" B="+A[2])}oc(ge,u-10,v,h,1)}!Ma||ia||Ta||Lb||0>V||(d.drawImage(F[V].can,F[V].xmin,F[V].ymin),oc(Hd,(F[V].xmin+F[V].xmax)/2,(F[V].ymin+F[V].ymax)/2,F[V].tip,0),Vc=!0)},ja=function(){var a;if(Wc)try{s.width=s.width;s.globalAlpha=1;if($b&&null!=Na&&0<=W&&Na[W].gotit)s.drawImage(Na[W],Q*ra[W],E*ra[W],aa*ra[W],H*ra[W],0,0,l.width,l.height);else if(S[w].gotit&&s.drawImage(S[w],Q,E,aa,H,0,0,l.width,l.height),null!=Z&&(s.globalAlpha=1,S[w].gotit))for(var b=0;b<Z.length;b+=4)s.drawImage(S[w],Z[b],Z[b+1],
Z[b+2],Z[b+3],Z[b],Z[b+1],Z[b+2],Z[b+3]);if(0<G){for(b=0;b<G;b++)a=null!=ma?ma[b]:b,B[a].checked&&($b&&null!=Oa&&0<=W&&Oa[W].gotit&&qd==a?s.drawImage(Oa[W],Q*ra[W],E*ra[W],aa*ra[W],H*ra[W],0,0,l.width,l.height):C[w][a].gotit&&(null!=Xa&&(s.globalAlpha=Xa[a]),null==jc||jc[a]?s.drawImage(C[w][a],Q,E,aa,H,0,0,l.width,l.height):s.drawImage(C[w][a],0,0)));if(null!=Ua)for(s.globalAlpha=1,b=0;b<G;b++)a=null!=ma?ma[b]:b,C[w][a].gotit&&B[a].checked&&Ua[a]&&s.drawImage(C[w][a],J[a][0],J[a][1],J[a][2],J[a][3],
J[a][0],J[a][1],J[a][2],J[a][3]);Lb&&va()}Td&&Pc();if(id)for(s.globalAlpha=1,a=0;a<La;a++)null!=D[a].icon&&D[a].icon.gotit&&s.drawImage(D[a].icon,D[a].x0,D[a].y0)}catch(c){K("Error:"+c)}},Pc=function(){if(fd&&ub>Aa){s.save();s.fillStyle="blue";s.strokeStyle="white";s.lineWidth=3;s.strokeRect(Lc,Mc,200,14);s.fillRect(Lc,Mc,Aa/ub*200,14);var a=s.measureText("Loading images").width;s.fillStyle="orange";s.font="14px arial";s.fillText("Loading images",Lc+100-a/2,Mc+11);s.restore()}else Td=!1},K=function(a){if(ha&&
xb&&!xb.closed)try{xb.document.write(a+"<br>")}catch(b){}},pe=function(){pa&&Oc(zb);be=w==k-1?md+ba:ba;ja();setTimeout(function(){se(pe)},be)}};
